version: "3.0"

services:
    cassandra:
        container_name: rednet-session-service-cassandra-sessions
        image: redis
        ports:
            - "6379:6379"
        networks:
            - rednet-network
    api:
        container_name: rednet-session-service
        build: ./session-service
        ports:
            - "8002:8002"
        depends_on:
            - cassandra
        restart: unless-stopped
        networks:
            - rednet-network
networks:
    rednet-network:
        external: true