server:
    port: 8002
    error:
        include-message: always
        include-binding-errors: always
spring:
    cassandra:
        port: 9042
        contact-points: localhost
rednet:
    app:
        access-token-expiration-ms: 60000
        access-token-secret-key: suF25ZudSgyzQSS9QgpaSyUt5XZZGtTayc22RlLe5IX1erTOz64mN5BarqeiPV2s
        api-token-issuer: rednet-agw
        api-token-secret-key: 301RJdFDpzEchd3y+4O7GUl3Ade2PNyyDtUx76AdPWpe0uYUW47MON9jtEUOmod9
        api-token-cookie-name: rednet-api-token
        refresh-token-expiration-ms: 172800000
        refresh-token-secret-key: a1yTJjPn3+N8p7y3bANWFg+mOpQH6WWrSfKq2NM4f9YFNsKK8U4VRx6Godo3OeEf
        auth-token-issuer: rednet-auth