server:
    port: 8002
    error:
        include-message: always
        include-binding-errors: always
spring:
    data:
        redis:
            host: localhost
            port: 6379
rednet:
    app:
